stages:
  - build
  - test
  - deploy

build-wedding:
  only:
  - master
  stage: build
  script:
  - pwd
  - $MAVEN_HOME/bin/mvn clean package

deploy-wedding:
  only:
  - master
  stage: deploy
  script:
  - pwd
  - docker build -t ycycqwedding .
  - docker run -p 9091:9091 ycycqwedding
