stages:
  - build
  - test
  - deploy

build-wedding:
  only:
  - master
  stage: build
  script:
  - pwd
  - $MAVEN_HOME/bin/mvn clean package
  - docker build -t ycycqwedding .
  - docker stop ycycqwedding
  - docker run --rm -p 2222:2222 -itd --restart=always ycycqwedding
