server:
  port: 2222
spring:
  datasource:
    username: liji
    password: Syx002183
    url: jdbc:mysql://172.31.213.8:3306/ycycqweddingtest?characterEncoding=utf-8&useSSL=false
    initialSize: 5
    maxActive: 40
    maxWait: 60000
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
wechat:
  appId: wxde61fb45f6d68a5f
  appSecret: 4b70a22117c2463cf55bbfd6739f65e0
logpath: ycycqweddingtest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
