server:
  port: 2222
spring:
  datasource:
    username: liji
    password: Syx002183
    url: jdbc:mysql://47.75.114.178/ycycqwedding?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true


